### ISSUE TITLE
ImportError: bad magic number in 'geo_map_cython_lib': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by ganliqiang** [songdejia/EAST-AutoTrainEval-pytorch#17]
the detail about the error is :Traceback (most recent call last):
  File "/home/user/east/EAST-pytorch/main.py", line 11, in <module>
    from data_utils import custom_dset, collate_fn
  File "/home/user/east/EAST-pytorch/data_utils.py", line 18, in <module>
    from geo_map_cython_lib import gen_geo_map
 i search a lot , but not solved this error,so how to solve the error to run the code correctly?thanks..

**Comment by wqtwjt1996** [comment]
Just delete all the *.pyc files in geo_map_cython_lib folder.

**Comment by Islanna** [comment]
> 
> 
> Just delete all the *.pyc files in geo_map_cython_lib folder.

In this case it starts to give the error "libpython2.7.so.1.0: cannot open shared object file: No such file or directory"

Does it mean this repo works only for Python2 ?

**Comment by wqtwjt1996** [comment]
You can try to run it on Python3, I used python3 and this problem was solved.

**Comment by ganliqiang** [comment]
> You can try to run it on Python3, I used python3 and this problem was solved.

i find this method before,but when i delete the _init__.pyc, new problem occur:
ImportError: dynamic module does not define module export function (PyInit_gen_geo_map);
the _init__.pyc ｉｓ downloaded from git repository.do you meet the same problem?

**Comment by decajcd** [comment]
> > You can try to run it on Python3, I used python3 and this problem was solved.
> 
> i find this method before,but when i delete the _init__.pyc, new problem occur:
> ImportError: dynamic module does not define module export function (PyInit_gen_geo_map);
> the _init__.pyc ｉｓ downloaded from git repository.do you meet the same problem?

Have you solved this problem

**Comment by wqtwjt1996** [comment]
ImportError: dynamic module does not define module export function (PyInit_gen_geo_map);
the init_.pyc
I did not meet this problem. But I guess it related to the OS you used. I used Win10.

**Comment by kalupiu** [comment]
> > Just delete all the *.pyc files in geo_map_cython_lib folder.
> 
> In this case it starts to give the error "libpython2.7.so.1.0: cannot open shared object file: No such file or directory"
> 
> Does it mean this repo works only for Python2 ?

I meet the same problem. Have you solved it now?

**Comment by kalupiu** [comment]
> > Just delete all the *.pyc files in geo_map_cython_lib folder.
> 
> In this case it starts to give the error "libpython2.7.so.1.0: cannot open shared object file: No such file or directory"
> 
> Does it mean this repo works only for Python2 ?

I met the same problem. Have anyone solved it yet?

**Comment by xxiaocui** [comment]
> 只需删除geo_map_cython_lib文件夹中的所有* .pyc文件即可。



> You can try to run it on Python3, I used python3 and this problem was solved.

python3.0？I used python3.7 and that can not

**Comment by xxiaocui** [comment]
> 有关该错误的详细信息是：跟踪（最近一次通话最近）：
> 文件“ /home/user/east/EAST-pytorch/main.py”，第11行，
> 从data_utils导入custom_dset，collat​​e_fn 
> 文件“ / home / user / east / EAST-pytorch / data_utils.py“，第18行，
> 来自geo_map_cython_lib import gen_geo_map 
> 我搜索了很多，但没有解决此错误，那么如何解决错误才能正确运行代码？

that is python3.0? I use python3.7,but the problem is not solved

**Comment by Hujiassd** [comment]
Use the ls -a command in geo_map_cython_lib to find all the .pyc files deleted.

**Comment by AaaGss** [comment]
![捕获](https://user-images.githubusercontent.com/53250398/67589225-888cff00-f78a-11e9-90a2-03ddcd804c0b.PNG)


when i trained main.py,i met this problem.how to do with?

**Comment by empowerszc** [comment]
> ![捕获](https://user-images.githubusercontent.com/53250398/67589225-888cff00-f78a-11e9-90a2-03ddcd804c0b.PNG)
> 
> when i trained main.py,i met this problem.how to do with?

I have also met this problem, and I solve it by run build_ext.sh, or directly input command 
`python setup.py build_ext --inplace`
Hope it works for you.

**Comment by AaaGss** [comment]
thank you



---Original---

**Comment by ranye92** [comment]
> ImportError: dynamic module does not define module export function (PyInit_gen_geo_map);
> the init_.pyc
> I did not meet this problem. But I guess it related to the OS you used. I used Win10.

I have the same problem and I use Win10 too. Have anyone solved this problem?  THANKS

**Comment by fengxiaoshuai** [comment]
删除__init__.pyc, 重新运行build_text.sh，python3.6, centos,docker有效

**Comment by xianyu-123** [comment]
> > ![捕获](https://user-images.githubusercontent.com/53250398/67589225-888cff00-f78a-11e9-90a2-03ddcd804c0b.PNG)
> > when i trained main.py,i met this problem.how to do with?
> 
> I have also met this problem, and I solve it by run build_ext.sh, or directly input command
> `python setup.py build_ext --inplace`
> Hope it works for you.

I used this way, not solve this problem... Unresolved reference 'gen_geo_map'

**Comment by xianyu-123** [comment]
> 删除__init__.pyc, 重新运行build_text.sh，python3.6, centos,docker有效

亲测有效，重命名也不行

**Comment by zhangjie-biu** [comment]
> > > Just delete all the *.pyc files in geo_map_cython_lib folder.
> > 
> > 
> > In this case it starts to give the error "libpython2.7.so.1.0: cannot open shared object file: No such file or directory"
> > Does it mean this repo works only for Python2 ?
> 
> I met the same problem. Have anyone solved it yet?

如果你删除了init_py遇到了上面的问题，可能是由于你没有在运行main.py前运行geo_map_cython_lib下的build_ext.sh脚本，你可能还需要安装cython。
